### ISSUE TITLE
Cannot determine a class of the requesting service 'undefined'

### ISSUE THREAD

**Issue by joonhuang** [rxdi/xmigrate#14]
Hitting error 'Cannot determine a class of the requesting service 'undefined'' while running command, `xmigrate status` with xmigrate.ts (minimal configuration)

**Comment by Stradivario** [comment]
Since i am using it at daily bases and i don't see any problems related with this particular error thus i have face it in @rxdi/core library when there is no dependency for particular provider when injecting values to dependency injection.

Please install latest version try how it will goes and if this error persist write here to re-open and investigate further.

Regards,
Kristiyan Tachev
